name: Run Hiddify Manager Install

on:
  workflow_dispatch:          # manual trigger

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hiddify-Manager repository
        uses: actions/checkout@v4
        with:
          repository: hiddify/Hiddify-Manager
          path: hiddify-manager     # clones into ./hiddify-manager

      - name: Run install script
        working-directory: hiddify-manager
        run: |
          # chmod +x install.sh
          sudo ./install.sh
